"""
Async entropy-based routing strategy.

Enables concurrent execution of SLM and LLM when high entropy is detected.
SLM continues generating speculatively while LLM runs asynchronously.
"""

import asyncio
import random
import time
from dataclasses import dataclass, field
from typing import Optional, Tuple, cast

import torch
import torch.nn.functional as F

from hybrid_generator.backends import BackendId, HybridBackend
from hybrid_generator.backends.hybrid import AsyncHybridBackend
from hybrid_generator.strategies.base import GenerationStrategy
from hybrid_generator.strategies.metrics import LiveMetricsTracker
from hybrid_generator.strategies.utils import (
    calculate_token_entropy,
    sample_token_flashinfer,
)


@dataclass
class SpeculativeBuffer:
    """Stores SLM's speculative generation state during async phase."""

    # Token IDs generated by SLM during speculation
    tokens: list[int] = field(default_factory=list)

    # Logits for each speculative token (before sampling)
    logits: list[torch.Tensor] = field(default_factory=list)

    # Entropies for each position
    entropies: list[float] = field(default_factory=list)

    # Starting position in generated_ids where speculation began
    divergence_pos: int = 0

    # SLM logits at divergence point (for verification)
    divergence_logits: Optional[torch.Tensor] = None

    def clear(self):
        """Clear all buffers."""
        self.tokens.clear()
        self.logits.clear()
        self.entropies.clear()
        self.divergence_logits = None

    def length(self) -> int:
        """Return number of speculative tokens."""
        return len(self.tokens)


@dataclass
class LLMResult:
    """Result from LLM async generation task."""

    token: int  # Generated token ID
    logits: torch.Tensor  # Logits at divergence point
    position: int  # Position in sequence


class AsyncEntropyStrategy(GenerationStrategy):
    """
    Async entropy-based routing strategy.

    When SLM encounters high entropy:
    1. Trigger LLM asynchronously to generate from divergence point
    2. SLM continues generating speculatively
    3. Stop when: (a) another high entropy, or (b) LLM completes
    4. Verify: Compare top-3 tokens at divergence point
    5. If match: accept SLM tokens, continue with SLM
       If mismatch: rollback SLM, use LLM's token
    """

    def generate(
        self,
        hybrid_backend: HybridBackend,
        tokenizer,
        prompt: str,
        max_new_tokens: int,
        temperature: float,
        top_k: int,
        top_p: float,
        min_p: float,
        device: str,
        threshold: float = 2.0,
        verbose: bool = False,
        report_live_metrics: bool = False,
        **kwargs,
    ) -> Tuple[str, dict]:
        """
        Generate using async entropy-based routing.

        Synchronous wrapper around async implementation for compatibility.
        """
        return asyncio.run(
            self.generate_async(
                hybrid_backend=hybrid_backend,
                tokenizer=tokenizer,
                prompt=prompt,
                max_new_tokens=max_new_tokens,
                temperature=temperature,
                top_k=top_k,
                top_p=top_p,
                min_p=min_p,
                device=device,
                threshold=threshold,
                verbose=verbose,
                report_live_metrics=report_live_metrics,
                **kwargs,
            )
        )

    async def generate_async(
        self,
        hybrid_backend: HybridBackend,
        tokenizer,
        prompt: str,
        max_new_tokens: int,
        temperature: float,
        top_k: int,
        top_p: float,
        min_p: float,
        device: str,
        threshold: float = 2.0,
        verbose: bool = False,
        report_live_metrics: bool = False,
        **kwargs,
    ) -> Tuple[str, dict]:
        """Main async generation implementation."""
        if not isinstance(hybrid_backend, HybridBackend):
            raise ValueError("AsyncEntropyStrategy requires a HybridBackend instance.")

        # Wrap with AsyncHybridBackend if needed
        if not isinstance(hybrid_backend, AsyncHybridBackend):
            hybrid_backend = AsyncHybridBackend(
                hybrid_backend.slm_backend, hybrid_backend.llm_backend
            )

        # 1. Initialize Session
        req_id = random.randint(0, 2**31 - 1)

        # Initialize live metrics tracker
        live_tracker = (
            LiveMetricsTracker(report_interval=100) if report_live_metrics else None
        )

        # 2. Prefill Phase (synchronous)
        inputs = tokenizer(prompt, return_tensors="pt").to(device)
        input_ids = inputs["input_ids"][0].tolist()
        prompt_len = len(input_ids)

        # Prefill both models
        slm_logits_all = hybrid_backend.forward(BackendId.SLM, req_id, input_ids)
        current_slm_logits = slm_logits_all[-1, :]

        llm_logits_all = hybrid_backend.forward(BackendId.LLM, req_id, input_ids)
        current_llm_logits = llm_logits_all[-1, :]

        # Track global generation state
        generated_ids = list(input_ids)

        # Track synchronization state
        slm_synced_len = prompt_len
        llm_synced_len = prompt_len

        eos_token_id = tokenizer.eos_token_id

        enable_stats_sync = kwargs.get("enable_stats_sync", False)
        if enable_stats_sync and device.startswith("cuda"):
            torch.cuda.synchronize()
        start_time = time.time()

        # Statistics
        slm_tokens = 0
        llm_tokens = 0
        decode_steps = 0
        speculation_attempts = 0
        speculation_accepted = 0
        speculation_rejected = 0
        total_speculation_length = 0
        cumprob_sum_accepted = {"slm": 0.0, "llm": 0.0}

        # Async state
        spec_buffer = SpeculativeBuffer()
        llm_task: Optional[asyncio.Task] = None

        # Helper to print/track
        def _process_token(next_token_id, model_used, entropy_val):
            token_text = tokenizer.decode([next_token_id], skip_special_tokens=True)
            if live_tracker:
                live_tracker.add_token(
                    model_used=model_used,
                    token_text=token_text,
                    entropy=entropy_val.item()
                    if hasattr(entropy_val, "item")
                    else entropy_val,
                    uncertainty=None,
                )
                if live_tracker.should_report():
                    live_tracker.print_progress()
            if verbose:
                print(f"{token_text}", end="", flush=True)
            return next_token_id == eos_token_id

        # 3. Main Generation Loop
        while len(generated_ids) - prompt_len < max_new_tokens:
            decode_steps += 1

            # Calculate entropy on current SLM logits
            entropy = calculate_token_entropy(current_slm_logits, temperature)

            # --- Case 1: Low entropy, no LLM task running ---
            if entropy < threshold and llm_task is None:
                # Normal SLM generation
                next_token_tensor = sample_token_flashinfer(
                    current_slm_logits.unsqueeze(0), temperature, top_k, top_p
                )
                next_token_id = cast(int, next_token_tensor.item())
                slm_tokens += 1
                generated_ids.append(next_token_id)

                # Update SLM state
                current_slm_logits = hybrid_backend.forward(
                    BackendId.SLM, req_id, [next_token_id]
                )[-1, :]
                slm_synced_len += 1

                if _process_token(next_token_id, "slm", entropy):
                    break

            # --- Case 2: High entropy detected, no LLM task running ---
            elif entropy >= threshold and llm_task is None:
                # Enter speculation mode
                speculation_attempts += 1
                spec_buffer.divergence_pos = len(generated_ids)
                spec_buffer.divergence_logits = current_slm_logits.clone()

                # Start LLM async task
                catchup_tokens = generated_ids[llm_synced_len:]
                llm_task = asyncio.create_task(
                    self._llm_generate_from_divergence(
                        hybrid_backend=hybrid_backend,
                        req_id=req_id,
                        catchup_tokens=catchup_tokens,
                        temperature=temperature,
                        top_k=top_k,
                        top_p=top_p,
                        divergence_pos=spec_buffer.divergence_pos,
                        cached_llm_logits=current_llm_logits
                        if not catchup_tokens
                        else None,
                    )
                )

                # Generate first speculative token immediately
                next_token_tensor = sample_token_flashinfer(
                    current_slm_logits.unsqueeze(0), temperature, top_k, top_p
                )
                next_token_id = cast(int, next_token_tensor.item())

                # Store in buffer
                spec_buffer.tokens.append(next_token_id)
                spec_buffer.logits.append(current_slm_logits.clone())
                spec_buffer.entropies.append(entropy.item())

                # Get next logits
                current_slm_logits = hybrid_backend.forward(
                    BackendId.SLM, req_id, [next_token_id]
                )[-1, :]

                # Continue to next iteration
                continue

            # --- Case 3: LLM task running (speculation in progress) ---
            elif llm_task is not None:
                # Check if LLM is done
                if llm_task.done():
                    # === Verification Phase ===
                    try:
                        llm_result = await llm_task
                    except Exception as e:
                        print(f"\nLLM async task failed: {e}, falling back to sync")
                        # Fallback: use synchronous LLM
                        catchup_tokens = generated_ids[llm_synced_len:]
                        if catchup_tokens:
                            llm_logits = hybrid_backend.forward(
                                BackendId.LLM, req_id, catchup_tokens
                            )
                            divergence_logits = llm_logits[-1, :]
                            llm_synced_len += len(catchup_tokens)
                        else:
                            divergence_logits = current_llm_logits

                        llm_token_tensor = sample_token_flashinfer(
                            divergence_logits.unsqueeze(0), temperature, top_k, top_p
                        )
                        llm_result = LLMResult(
                            token=llm_token_tensor.item(),
                            logits=divergence_logits,
                            position=spec_buffer.divergence_pos,
                        )

                    # LLM cache has only advanced to the divergence position.
                    # Do not assume the sampled token was consumed.
                    llm_synced_len = spec_buffer.divergence_pos
                    current_llm_logits = llm_result.logits

                    # Verify logits at divergence point
                    accept, verify_stats = self._verify_logits(
                        slm_logits=spec_buffer.divergence_logits,
                        llm_logits=llm_result.logits,
                        temperature=temperature,
                        top_k=3,
                    )

                    if accept:
                        # Accept speculation
                        generated_ids.extend(spec_buffer.tokens)
                        slm_synced_len = len(generated_ids)
                        # Keep LLM lagging; it will catch up when needed.
                        speculation_accepted += 1
                        total_speculation_length += spec_buffer.length()

                        # Track cumulative probabilities
                        cumprob_sum_accepted["slm"] += verify_stats.get(
                            "slm_cumprob", 0.0
                        )
                        cumprob_sum_accepted["llm"] += verify_stats.get(
                            "llm_cumprob", 0.0
                        )

                        # Print accepted speculative tokens
                        for token_id, ent in zip(
                            spec_buffer.tokens, spec_buffer.entropies
                        ):
                            if _process_token(token_id, "slm", ent):
                                spec_buffer.clear()
                                llm_task = None
                                break

                        # current_slm_logits already updated during speculation

                    else:
                        # Reject - rollback and use LLM
                        current_slm_logits = self._handle_verification_failure(
                            hybrid_backend=hybrid_backend,
                            req_id=req_id,
                            spec_buffer=spec_buffer,
                            llm_token=llm_result.token,
                        )
                        slm_synced_len = spec_buffer.divergence_pos + 1
                        llm_synced_len = spec_buffer.divergence_pos
                        generated_ids = generated_ids[: spec_buffer.divergence_pos]
                        generated_ids.append(llm_result.token)
                        speculation_rejected += 1

                        llm_tokens += 1
                        if _process_token(llm_result.token, "llm", entropy):
                            spec_buffer.clear()
                            llm_task = None
                            break

                    # Reset state
                    spec_buffer.clear()
                    llm_task = None

                    if generated_ids[-1] == eos_token_id:
                        break

                    continue

                # LLM still running - check if SLM should stop speculating
                if entropy >= threshold:
                    # Stop 1: Another high entropy encountered
                    # Wait for LLM to finish
                    llm_result = await llm_task
                    llm_synced_len = spec_buffer.divergence_pos
                    current_llm_logits = llm_result.logits

                    # Proceed to verification (same logic as above)
                    accept, verify_stats = self._verify_logits(
                        slm_logits=spec_buffer.divergence_logits,
                        llm_logits=llm_result.logits,
                        temperature=temperature,
                        top_k=3,
                    )

                    if accept:
                        generated_ids.extend(spec_buffer.tokens)
                        slm_synced_len = len(generated_ids)
                        # Keep LLM lagging; it will catch up when needed.
                        speculation_accepted += 1
                        total_speculation_length += spec_buffer.length()
                        cumprob_sum_accepted["slm"] += verify_stats.get(
                            "slm_cumprob", 0.0
                        )
                        cumprob_sum_accepted["llm"] += verify_stats.get(
                            "llm_cumprob", 0.0
                        )

                        for token_id, ent in zip(
                            spec_buffer.tokens, spec_buffer.entropies
                        ):
                            if _process_token(token_id, "slm", ent):
                                spec_buffer.clear()
                                llm_task = None
                                break

                        # current_slm_logits already updated during speculation

                    else:
                        current_slm_logits = self._handle_verification_failure(
                            hybrid_backend=hybrid_backend,
                            req_id=req_id,
                            spec_buffer=spec_buffer,
                            llm_token=llm_result.token,
                        )
                        slm_synced_len = spec_buffer.divergence_pos + 1
                        llm_synced_len = spec_buffer.divergence_pos
                        generated_ids = generated_ids[: spec_buffer.divergence_pos]
                        generated_ids.append(llm_result.token)
                        speculation_rejected += 1
                        llm_tokens += 1
                        if _process_token(llm_result.token, "llm", entropy):
                            spec_buffer.clear()
                            llm_task = None
                            break

                    spec_buffer.clear()
                    llm_task = None

                    if generated_ids[-1] == eos_token_id:
                        break

                    continue

                # Generate speculative token
                next_token_tensor = sample_token_flashinfer(
                    current_slm_logits.unsqueeze(0), temperature, top_k, top_p
                )
                next_token_id = cast(int, next_token_tensor.item())

                # Store in buffer
                spec_buffer.tokens.append(next_token_id)
                spec_buffer.logits.append(current_slm_logits.clone())
                spec_buffer.entropies.append(entropy.item())

                # Get next logits
                current_slm_logits = hybrid_backend.forward(
                    BackendId.SLM, req_id, [next_token_id]
                )[-1, :]
                # Don't update slm_synced_len here - will update if accepted

        # 4. Cleanup
        hybrid_backend.free(BackendId.SLM, req_id)
        hybrid_backend.free(BackendId.LLM, req_id)

        # Note: shutdown() will be called by exit() in the example script
        # Do not call it here to allow backend reuse

        if enable_stats_sync and device.startswith("cuda"):
            torch.cuda.synchronize()
        end_time = time.time()

        # Statistics
        acceptance_rate = (
            speculation_accepted / speculation_attempts
            if speculation_attempts > 0
            else 0.0
        )
        avg_speculation_length = (
            total_speculation_length / speculation_attempts
            if speculation_attempts > 0
            else 0.0
        )
        avg_slm_cumprob = (
            cumprob_sum_accepted["slm"] / speculation_accepted
            if speculation_accepted > 0
            else 0.0
        )
        avg_llm_cumprob = (
            cumprob_sum_accepted["llm"] / speculation_accepted
            if speculation_accepted > 0
            else 0.0
        )

        stats = {
            "total_tokens": len(generated_ids) - prompt_len,
            "slm_tokens": slm_tokens,
            "llm_tokens": llm_tokens,
            "decode_steps": decode_steps,
            "elapsed_time": end_time - start_time,
            "threshold": threshold,
            # Async-specific metrics
            "speculation_attempts": speculation_attempts,
            "speculation_accepted": speculation_accepted,
            "speculation_rejected": speculation_rejected,
            "acceptance_rate": acceptance_rate,
            "avg_speculation_length": avg_speculation_length,
            "avg_slm_cumprob_accepted": avg_slm_cumprob,
            "avg_llm_cumprob_accepted": avg_llm_cumprob,
        }

        return tokenizer.decode(
            generated_ids[prompt_len:], skip_special_tokens=True
        ), stats

    async def _llm_generate_from_divergence(
        self,
        hybrid_backend: AsyncHybridBackend,
        req_id: int,
        catchup_tokens: list[int],
        temperature: float,
        top_k: int,
        top_p: float,
        divergence_pos: int,
        cached_llm_logits: Optional[torch.Tensor] = None,
    ) -> LLMResult:
        """
        Async task: LLM catches up and generates token.

        Args:
            hybrid_backend: AsyncHybridBackend instance
            req_id: Request ID
            catchup_tokens: Tokens LLM needs to catch up
            temperature: Sampling temperature
            top_k: Top-k sampling parameter
            top_p: Top-p sampling parameter
            divergence_pos: Position where divergence occurred
            cached_llm_logits: Cached LLM logits if already available

        Returns:
            LLMResult containing generated token and logits
        """
        # Catch up LLM if needed
        if catchup_tokens:
            logits = await hybrid_backend.forward_async(
                BackendId.LLM, req_id, catchup_tokens
            )
            divergence_logits = logits[-1, :]
        elif cached_llm_logits is not None:
            # Use cached logits (e.g., from prefill)
            divergence_logits = cached_llm_logits
        else:
            # Should not happen, but handle defensively
            raise ValueError("No catchup tokens and no cached logits for LLM")

        # Generate token from divergence point
        token_tensor = sample_token_flashinfer(
            divergence_logits.unsqueeze(0), temperature, top_k, top_p
        )

        return LLMResult(
            token=token_tensor.item(),
            logits=divergence_logits,
            position=divergence_pos,
        )

    def _verify_logits(
        self,
        slm_logits: torch.Tensor,
        llm_logits: torch.Tensor,
        temperature: float,
        top_k: int = 3,
        prob_threshold: float = 0.8,
    ) -> Tuple[bool, dict]:
        """
        Verify if SLM and LLM agree at divergence point.

        Checks:
        1. Top-k token IDs match (as sets)
        2. Cumulative probability of top-k >= prob_threshold

        Args:
            slm_logits: SLM logits at divergence point
            llm_logits: LLM logits at divergence point
            temperature: Sampling temperature
            top_k: Number of top tokens to compare
            prob_threshold: Minimum cumulative probability

        Returns:
            (accept: bool, stats: dict)
        """
        # Apply temperature
        slm_scaled = slm_logits / temperature
        llm_scaled = llm_logits / temperature

        # Get top-k tokens
        slm_topk_vals, slm_topk_ids = torch.topk(slm_scaled, k=top_k)
        llm_topk_vals, llm_topk_ids = torch.topk(llm_scaled, k=top_k)

        # Check 1: Top-k sets match
        slm_set = set(slm_topk_ids.tolist())
        llm_set = set(llm_topk_ids.tolist())

        if slm_set != llm_set:
            return False, {
                "reason": "top_k_mismatch",
                "slm_top_k": list(slm_set),
                "llm_top_k": list(llm_set),
            }

        # Check 2: Cumulative probability
        slm_probs = F.softmax(slm_scaled, dim=-1)
        llm_probs = F.softmax(llm_scaled, dim=-1)

        slm_cumprob = slm_probs[slm_topk_ids].sum().item()
        llm_cumprob = llm_probs[llm_topk_ids].sum().item()
        min_cumprob = min(slm_cumprob, llm_cumprob)

        if min_cumprob < prob_threshold:
            return False, {
                "reason": "low_cumprob",
                "slm_cumprob": slm_cumprob,
                "llm_cumprob": llm_cumprob,
                "min_cumprob": min_cumprob,
            }

        return True, {
            "reason": "accepted",
            "slm_cumprob": slm_cumprob,
            "llm_cumprob": llm_cumprob,
        }

    def _handle_verification_failure(
        self,
        hybrid_backend: HybridBackend,
        req_id: int,
        spec_buffer: SpeculativeBuffer,
        llm_token: int,
    ) -> torch.Tensor:
        """
        Rollback SLM and synchronize with LLM result.

        Args:
            hybrid_backend: HybridBackend instance
            req_id: Request ID
            spec_buffer: Speculative buffer
            llm_token: Token generated by LLM

        Returns:
            Updated current_slm_logits
        """
        # 1. Rollback SLM to divergence point
        target_len = spec_buffer.divergence_pos
        hybrid_backend.rollback(BackendId.SLM, req_id, target_len)

        # 2. Feed LLM's token to SLM
        slm_logits = hybrid_backend.forward(BackendId.SLM, req_id, [llm_token])
        current_slm_logits = slm_logits[-1, :]

        return current_slm_logits
